android.enableAppCompileTimeRClass=true
android.enableR8.fullMode=true
android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.native.buildOutput=verbose
android.nonTransitiveRClass=true
android.r8.maxWorkers=4
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
org.gradle.vfs.watch=true
